name: Test Schedule
on:
  # schedule:
  #   - cron: '*/2 * * * *' 

jobs:
  Test-Schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Display Message
        run: echo "This workflow was triggered at $(date)"
