on:
  schedule:
    - cron: '43 7 * * *'
  workflow_dispatch:
    inputs:
      human:
        description: Did a human start this workflow?
        type: boolean
        default: true
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"
