name: Test Schedule
on:
  schedule:
    - cron: '52 7 * * *'  # Runs every day at 7:43 AM UTC
  workflow_dispatch:
    inputs:
      human:
        description: Did a human start this workflow?
        type: boolean
        default: true

jobs:
  Test-Schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Display Message
        run: echo "This workflow was triggered at $(date)"
